builds:
  - binary: gopsa
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - 386
    ignore:
      - goos: darwin
        goarch: 386
      - goos: linux
        goarch: 386
archive:
  name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  format: binary
  replacements:
    darwin: mac
